CVC4_HOME=<non-existing-path>
CXXFLAGS=-no-pie -g

smtlib2cvc4.out: smtlib2cvc4.cpp
	$(CXX) $(CXXFLAGS) $(DEBUG) -std=c++11 -I$(CVC4_HOME)/src -I$(CVC4_HOME)/src/include -I$(CVC4_HOME)/build/src -I$(CVC4_HOME)/build/src/include -o smtlib2cvc4.out smtlib2cvc4.cpp -L$(CVC4_HOME)/build/src -L$(CVC4_HOME)/build/src/parser -lcvc4 -lcvc4parser -lgmp -D__BUILDING_CVC4PARSERLIB

clean:
	rm -rf *.out

test: 
	./test.sh tests/test.smt2
